### ISSUE TITLE
Logo For Sign Language

### ISSUE THREAD

**Issue by zularizal** [Mquinn960/sign-language#1]
Hi @Mquinn960 , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. Don't worry about fees, it's free for you. What do you think?

**Comment by Mquinn960** [comment]
Hello! Feel free to submit a PR - this project is still in development hence why the ReadMe is quite sparse

**Comment by zularizal** [comment]
Hi @Mquinn960 , sorry late reply, I want to know what this app is? and how this app works, can you describe it? I need this to design the logo.

**Comment by Mquinn960** [comment]
Hello there, apologies for the delay, this is a Sign Language Recognition mobile app using machine learning. As this is a degree program, any contributions to this project will be incorporated after the end of term in 2019.
