### ISSUE TITLE
Hello :)

### ISSUE THREAD

**Issue by JmKanmo** [Mquinn960/sign-language#11]
I'm really interested in your project :) 

I'm running your source code. But, it can't understand many alphabets in the Sign Language MNIST.  I downloaded train.xml file.  But, I think it didn't train enough.  

So, I wanna make train.xml file.  I did read your guideline. there are dataset - creator project and offline-trainer project.

I succeed running dataset-creator. But, I couldn't success offline-trainer. 

I'm first to install intelli j - IDEA.  I feel like intelli j is really good IDE.  I need to study and search it. 
 Anyway, Above all,  It's not easy to success to run Offline-trainer depending on the  README.md 's  instructions because I don't have enough background acknowledge. 

So, could you upload well-trained train.xml file in the README.md?  please. 

Or, If you have enough time, it'd pretty better upload some explanation about running project video at your youtube channel !         

Thank you for reading my help

**Comment by Mquinn960** [comment]
Hello!

Thank you for your interest in the project. I'll try to go through your points one by one:

1. The trained.xml file I offer for download in the README was trained on my own ASL dataset, so it should work fairly well on real world data, but I'm not sure how you're testing the MNIST dataset with this.

2. I'm glad you were able to use the dataset creator

3. IntelliJ IDEA is a great IDE for Java, but you don't -have- to use this. Using another editor and Maven for building is perfectly viable, but I can't support the use of other IDEs as it's a purely scientific project, hope you are able to use IntelliJ IDEA to make your life easier.

4. I realise the README files are quite long and potentially confusion, what I will do is write up a recommended workflow for using the program(s) together, in a more step-by-step fashion and place it in a Gist or something so hopefully this helps.

5. I have 80 trained XML files from my research work, but they are very large, some upwards of 1Gb so unfortunately I can't host them all here. If I am able to write up some clearer instructions (see 4. above) then hopefully you can create your own.

6. A video explanation is a great idea! If I have time I'd love to create a sample video showing the use of the projects.

I am quite busy with work at the moment but I will try to upload a guide this weekend for you. Again, I appreciate your patience as this is a scientific project and perhaps not very easy to use currently.

Kind regards,

Matt

**Comment by JmKanmo** [comment]
Thank you so much about your kind reply ;)
